spring.application.name=backend
spring.datasource.url=jdbc:h2:mem:cateringdb
spring.datasource.driverClassName=org.h2.Driver
# for in memory db
spring.jpa.hibernate.ddl-auto=create-drop

# for actual db
#spring.jpa.hibernate.ddl-auto=update

server.port=8080
