spring.application.name=backend

# Supabase PostgreSQL Connection (IPv4 Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jtczekmyflamlhhszykh
spring.datasource.password=Khaula16CMS
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Server config
server.port=8080